title: "antoinejaunard.com"
description: "documentation"
main_url: "https://antoinejaunard.com"
introduction: "Continuous process ✄ This website ☼ is my digital studio, a place where I can experiment without ⁂ constraints. It's also my personal assistant, it helps me when I'm not sure how to do ✿ something I've done before. It invites me to write (and then find) my personal knowledge ⧉ online. Welcome&nbsp;✺"
navigation:
  "antoinejaunard.com": "index"
  "content": "content"
  "flux": "flux"
  "about": "about"
flux:
  visibility: True
  title: "flux"
  slug: "flux"
footer: 'antoinejaunard.com ☼&nbsp;2022 — [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) — [RSS Feed](https://antoinejaunard.com/rss.xml)'